config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :sales
  resources :claims
  resources :orders do
    member do
      get 'approve'
      get 'reject'
    end
  end
  mount RailsAdmin::Engine => '/fapp', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/claim.rb
class Claim < ApplicationRecord
  has_paper_trail
  belongs_to :user, optional: false

  has_many :assets
  has_attached_file :asset
  validates_attachment_content_type :asset, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']

  delegate :name, :to => :user, :prefix => :user, :allow_nil => true
  validates :name, presence: true
  validates :user, presence: true
  validates :description, presence: true
  validates :amount, presence: true, numericality: true, :format => { :with => /\A\d+\.*\d{0,2}\z/ }
  validates :vendor, presence: true
  validates :category, presence: true
  validates :aasm_state, presence: true

  scope :pending,   ->{ where(aasm_state: 'pending')  }
  scope :approved,  ->{ where(aasm_state: 'approved')  }
  scope :submitted,  ->{ where(aasm_state: 'ordered')  }
  scope :received,   ->{ where(aasm_state: 'received')  }
  scope :rejected,   ->{ where(aasm_state: 'rejected')  }

  @@notifier = Slack::Notifier.new ENV["WEBHOOK_URL"] do
    defaults channel: "#logistics",
             username: "fApper - Claims"
  end

  def after_import_save(record)
    self.update_attribute(:user_id, PaperTrail.whodunnit)
    @@notifier.post text: "Claim #" + self.id.to_s + " awaiting approval. \nClaim created by " + User.find(PaperTrail.whodunnit).name.to_s + " - " + self.name.to_s + ": $" + self.amount.to_s
  end

  def create_associated_image(asset)
    assets.create(asset: asset)
  end

  rails_admin do
    include_all_fields
    configure :aasm_state do
      read_only true
    end
    field :aasm_state, :enum do
      enum do
        bindings[:object].aasm.states(:permitted => true).map(&:name)
      end
    end
    field :amount do
      formatted_value do # used in form views
        number_to_currency(value, :unit => "$")
      end
      pretty_value do # used in form views
        number_to_currency(value, :unit => "$")
      end
    end
    list do
      scopes [nil, 'pending', 'approved', 'submitted', 'received', 'rejected']
    end
  end

  include AASM
  aasm do
    state :pending, :initial => true
    state :approved
    state :submitted
    state :received
    state :rejected

    event :approve do
      transitions :from => [:pending, :rejected], :to => :approved
      after do
        @@notifier.ping "Claim #" + self.id.to_s + " approved by " + self.user.name + "\n Item: " + self.name + ", $" + self.amount.to_s
      end
    end

    event :submit do
      transitions :from => :approved, :to => :submitted
      after do
        @@notifier.ping "Claim #" + self.id.to_s + " submitted by " + self.user.name + "\n Item: " + self.name + ", $" + self.amount.to_s
      end
    end

    event :receive do
      transitions :from => :submitted, :to => :received
      after do
        @@notifier.ping "Claim #" + self.id.to_s + " received by " + self.user.name + "\n Item: " + self.name + ", $" + self.amount.to_s
      end
    end

    event :undo do
      transitions :from => :received, :to => :submitted
      after do
        @@notifier.ping "Claim #" + self.id.to_s + " undo-ed state to 'submitted' by " + self.user.name + "\n Item: " + self.name + ", $" + self.amount.to_s
      end
    end

    event :reject do
      transitions :from => [:pending, :approved, :submitted], :to => :rejected
      after do
        @@notifier.ping "Claim #" + self.id.to_s + " rejected by " + self.user.name + "\n Item: " + self.name + ", $" + self.amount.to_s
      end
    end
  end

  extend Enumerize
  enumerize :aasm_state, in: aasm.states

end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  before_action :set_claim, only: [:show, :edit, :update, :destroy]

  # GET /claims
  # GET /claims.json
  def index
    @claims = Claim.all
  end

  # GET /claims/1
  # GET /claims/1.json
  def show
  end

  # GET /claims/new
  def new
    @claim = Claim.new
  end

  # GET /claims/1/edit
  def edit
  end

  # POST /claims
  # POST /claims.json
  def create
    @claim = Claim.new(claim_params)

    respond_to do |format|
      if @claim.save
        format.html { redirect_to @claim, notice: 'Claim was successfully created.' }
        format.json { render :show, status: :created, location: @claim }
      else
        format.html { render :new }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /claims/1
  # PATCH/PUT /claims/1.json
  def update
    respond_to do |format|
      if @claim.update(claim_params)
        format.html { redirect_to @claim, notice: 'Claim was successfully updated.' }
        format.json { render :show, status: :ok, location: @claim }
      else
        format.html { render :edit }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /claims/1
  # DELETE /claims/1.json
  def destroy
    @claim.destroy
    respond_to do |format|
      format.html { redirect_to claims_url, notice: 'Claim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_claim
      @claim = Claim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def claim_params
      params.require(:claim).permit(:name, :description, :amount)
    end
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/views/claims/_form.html.erb
<%= form_for(claim) do |f| %>
  <% if claim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(claim.errors.count, "error") %> prohibited this claim from being saved:</h2>

      <ul>
      <% claim.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/claims/edit.html.erb
<h1>Editing Claim</h1>

<%= render 'form', claim: @claim %>

<%= link_to 'Show', @claim %> |
<%= link_to 'Back', claims_path %>

app/views/claims/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Claims</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @claims.each do |claim| %>
      <tr>
        <td><%= claim.name %></td>
        <td><%= claim.description %></td>
        <td><%= claim.amount %></td>
        <td><%= link_to 'Show', claim %></td>
        <td><%= link_to 'Edit', edit_claim_path(claim) %></td>
        <td><%= link_to 'Destroy', claim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Claim', new_claim_path %>

app/views/claims/new.html.erb
<h1>New Claim</h1>

<%= render 'form', claim: @claim %>

<%= link_to 'Back', claims_path %>

app/views/claims/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @claim.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @claim.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @claim.amount %>
</p>

<%= link_to 'Edit', edit_claim_path(@claim) %> |
<%= link_to 'Back', claims_path %>